spring.application.name=crm


#
# JDBC properties
#

server.port=9090
# Database Connection
spring.datasource.url=jdbc:postgresql://ep-snowy-sea-addrmuwh-pooler.c-2.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_wDZWGkTC0sg3&sslmode=require&channelBinding=require
spring.datasource.password=npg_wDZWGkTC0sg3
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate & JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=ZhyQkQVrTlpkaaiQjxWkHCA0quxrQwmV9ylIeEk37BfuXhUXs8lQrjkk6aUogvf5IHQ11Oml0IJeiDalQ4vWxQ==
